### Importación de datos

In [75]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [6]:
ingreso_total = tienda['Precio'].sum()
ingreso_total2 = tienda2['Precio'].sum()
ingreso_total3 = tienda3['Precio'].sum()
ingreso_total4 = tienda4['Precio'].sum()

In [17]:
print(f'Los ingresos de cada tienda son: \nPara la tienda 1: {ingreso_total}$.\nPara la tienda 2: {ingreso_total2}$.\nPara la tienda 3: {ingreso_total3}$.\nPara la tienda 4: {ingreso_total4}$.')

Los ingresos de cada tienda son:
Para la tienda 1: 1150880400.0$.
Para la tienda 2: 1116343500.0$.
Para la tienda 3: 1098019600.0$.
Para la tienda 4: 1038375700.0$.

# 2. Ventas por categoría

In [23]:
tienda['Categoría del Producto'].unique()

array(['Electrónicos', 'Muebles', 'Juguetes', 'Electrodomésticos',
       'Artículos para el hogar', 'Deportes y diversión', 'Libros',
       'Instrumentos musicales'], dtype=object)

In [43]:
venta_categoria_tienda = tienda.groupby('Categoría del Producto')[['Categoría del Producto']].value_counts().reset_index(name='Cantidad de Ventas').sort_values('Cantidad de Ventas', ascending=False)
venta_categoria_tienda

    Categoría del Producto  Cantidad de Ventas
7                  Muebles                 465
3             Electrónicos                 448
5                 Juguetes                 324
2        Electrodomésticos                 312
1     Deportes y diversión                 284
4   Instrumentos musicales                 182
6                   Libros                 173
0  Artículos para el hogar                 171

In [45]:
venta_categoria_tienda2 = tienda2.groupby('Categoría del Producto')[['Categoría del Producto']].value_counts().reset_index(name='Cantidad de Ventas').sort_values('Cantidad de Ventas', ascending=False)
venta_categoria_tienda2

    Categoría del Producto  Cantidad de Ventas
7                  Muebles                 442
3             Electrónicos                 422
5                 Juguetes                 313
2        Electrodomésticos                 305
1     Deportes y diversión                 275
4   Instrumentos musicales                 224
6                   Libros                 197
0  Artículos para el hogar                 181

In [46]:
venta_categoria_tienda3 = tienda3.groupby('Categoría del Producto')[['Categoría del Producto']].value_counts().reset_index(name='Cantidad de Ventas').sort_values('Cantidad de Ventas', ascending=False)
venta_categoria_tienda3

    Categoría del Producto  Cantidad de Ventas
7                  Muebles                 499
3             Electrónicos                 451
5                 Juguetes                 315
2        Electrodomésticos                 278
1     Deportes y diversión                 277
6                   Libros                 185
0  Artículos para el hogar                 177
4   Instrumentos musicales                 177

In [47]:
venta_categoria_tienda4 = tienda4.groupby('Categoría del Producto')[['Categoría del Producto']].value_counts().reset_index(name='Cantidad de Ventas').sort_values('Cantidad de Ventas', ascending=False)
venta_categoria_tienda4

    Categoría del Producto  Cantidad de Ventas
7                  Muebles                 480
3             Electrónicos                 451
5                 Juguetes                 338
1     Deportes y diversión                 277
2        Electrodomésticos                 254
0  Artículos para el hogar                 201
6                   Libros                 187
4   Instrumentos musicales                 170

# 3. Calificación promedio de la tienda

In [40]:
promedio_tienda = tienda.Calificación.mean().round(2)
promedio_tienda2 = tienda2.Calificación.mean().round(2)
promedio_tienda3 = tienda3.Calificación.mean().round(2)
promedio_tienda4 = tienda4.Calificación.mean().round(2)

In [41]:
print(f'Calificacion promedio de cada tienda:\nTienda 1: {promedio_tienda}.\nTienda 2: {promedio_tienda2}.\nTienda 3: {promedio_tienda3}.\nTienda 4: {promedio_tienda4}.')

Calificacion promedio de cada tienda:
Tienda 1: 3.98.
Tienda 2: 4.04.
Tienda 3: 4.05.
Tienda 4: 4.0.

# 4. Productos más y menos vendidos

In [94]:
tienda.Producto.value_counts().sort_values(ascending=False)

Producto
Microondas                     60
TV LED UHD 4K                  60
Armario                        60
Secadora de ropa               58
Mesa de noche                  56
Bloques de construcción        56
Balón de baloncesto            55
Bicicleta                      54
Vaso térmico                   54
Refrigerador                   54
Impresora                      54
Batería                        53
Cubertería                     52
Carrito de control remoto      52
Modelado predictivo            51
Auriculares                    50
Ajedrez de madera              49
Iphone 15                      49
Lavavajillas                   48
Lavadora de ropa               47
Guitarra eléctrica             47
Guitarra acústica              46
Sofá reclinable                46
Silla de oficina               46
Estufa                         45
Cama box                       44
Kit de bancas                  44
Smart TV                       44
Cama king                      44
Cubo mágico 8x8                44
Mesa de centro                 44
Set de ollas                   43
Smartwatch                     43
Juego de mesa                  43
Balón de voleibol              42
Dashboards con Power BI        42
Tablet ABXY                    42
Sillón                         41
Iniciando en programación      41
Set de vasos                   41
Asistente virtual              40
Muñeca bebé                    40
Mesa de comedor                40
Dinosaurio Rex                 40
Cuerda para saltar             40
Mochila                        39
Ciencia de datos con Python    39
Pandereta                      36
Olla de presión                35
Auriculares con micrófono      33
Celular ABXY                   33
Name: count, dtype: int64

In [93]:
tienda2.Producto.value_counts().sort_values(ascending=False)

Producto
Iniciando en programación      65
Microondas                     62
Batería                        61
Guitarra acústica              58
Pandereta                      58
Secadora de ropa               57
Iphone 15                      55
Bloques de construcción        54
Armario                        54
Set de ollas                   52
Cuerda para saltar             50
Lavadora de ropa               49
Silla de oficina               49
Refrigerador                   49
Muñeca bebé                    48
Carrito de control remoto      47
Guitarra eléctrica             47
Cama box                       47
Vaso térmico                   47
Modelado predictivo            46
Balón de voleibol              46
Set de vasos                   46
Lavavajillas                   46
Kit de bancas                  45
Cama king                      45
Bicicleta                      45
Mochila                        45
Cubo mágico 8x8                45
Ajedrez de madera              45
Mesa de centro                 45
TV LED UHD 4K                  45
Tablet ABXY                    44
Smartwatch                     44
Mesa de noche                  44
Olla de presión                44
Auriculares con micrófono      44
Sofá reclinable                44
Dashboards con Power BI        43
Ciencia de datos con Python    43
Balón de baloncesto            42
Estufa                         42
Dinosaurio Rex                 42
Celular ABXY                   41
Smart TV                       40
Cubertería                     39
Asistente virtual              38
Auriculares                    37
Sillón                         35
Mesa de comedor                34
Impresora                      34
Juego de mesa                  32
Name: count, dtype: int64

In [92]:
tienda3.Producto.value_counts().sort_values(ascending=False)

Producto
Kit de bancas                  57
Mesa de comedor                56
Cama king                      56
Set de ollas                   55
Mesa de noche                  55
Smart TV                       54
Estufa                         53
Cuerda para saltar             53
Modelado predictivo            53
Carrito de control remoto      52
Lavavajillas                   52
Bicicleta                      52
Juego de mesa                  52
Pandereta                      51
Impresora                      50
Refrigerador                   50
Balón de baloncesto            50
Armario                        49
Balón de voleibol              48
Tablet ABXY                    48
Sillón                         47
Guitarra acústica              47
Olla de presión                47
Ajedrez de madera              47
Ciencia de datos con Python    46
Iphone 15                      46
Dinosaurio Rex                 46
Silla de oficina               46
Smartwatch                     46
Cama box                       46
Iniciando en programación      46
Secadora de ropa               45
Sofá reclinable                45
Celular ABXY                   44
Cubo mágico 8x8                44
Auriculares                    43
TV LED UHD 4K                  42
Mesa de centro                 42
Lavadora de ropa               42
Batería                        41
Dashboards con Power BI        40
Cubertería                     39
Muñeca bebé                    39
Auriculares con micrófono      39
Asistente virtual              39
Vaso térmico                   38
Guitarra eléctrica             38
Set de vasos                   36
Mochila                        36
Microondas                     36
Bloques de construcción        35
Name: count, dtype: int64

In [91]:
tienda4.Producto.value_counts().sort_values(ascending=False)

Producto
Cama box                       62
Cubertería                     59
Dashboards con Power BI        56
Cama king                      56
Carrito de control remoto      55
Mesa de comedor                55
Mesa de noche                  55
Smart TV                       54
Bloques de construcción        54
Pandereta                      52
Impresora                      50
Modelado predictivo            50
Asistente virtual              50
Set de ollas                   50
Balón de baloncesto            50
Vaso térmico                   48
Iphone 15                      48
Muñeca bebé                    48
Batería                        48
Balón de voleibol              48
Juego de mesa                  48
Microondas                     48
Estufa                         47
Cubo mágico 8x8                47
Sofá reclinable                47
Dinosaurio Rex                 47
Olla de presión                46
Set de vasos                   46
Tablet ABXY                    45
Sillón                         45
Bicicleta                      45
Mesa de centro                 44
Auriculares                    44
Lavavajillas                   43
Cuerda para saltar             43
Iniciando en programación      43
Mochila                        43
Auriculares con micrófono      42
Kit de bancas                  42
TV LED UHD 4K                  40
Secadora de ropa               40
Silla de oficina               40
Celular ABXY                   39
Ajedrez de madera              39
Smartwatch                     39
Lavadora de ropa               38
Refrigerador                   38
Ciencia de datos con Python    38
Guitarra acústica              37
Armario                        34
Guitarra eléctrica             33
Name: count, dtype: int64

In [99]:
conteo_productos = tienda.Producto.value_counts()
mas_vendido = conteo_productos[conteo_productos==tienda.Producto.value_counts().max()]
menos_vendido = conteo_productos[conteo_productos==tienda.Producto.value_counts().min()]

In [98]:
conteo_productos2 = tienda2.Producto.value_counts()
mas_vendido2 = conteo_productos2[conteo_productos2==tienda2.Producto.value_counts().max()]
menos_vendido2 = conteo_productos2[conteo_productos2==tienda2.Producto.value_counts().min()]

In [97]:
conteo_productos3 = tienda3.Producto.value_counts()
mas_vendido3 = conteo_productos3[conteo_productos3==tienda3.Producto.value_counts().max()]
menos_vendido3 = conteo_productos3[conteo_productos3==tienda3.Producto.value_counts().min()]

In [90]:
conteo_productos4 = tienda4.Producto.value_counts()
mas_vendido4 = conteo_productos4[conteo_productos4==tienda4.Producto.value_counts().max()]
menos_vendido4 = conteo_productos4[conteo_productos4==tienda4.Producto.value_counts().min()]

Producto
Cama box    62
Name: count, dtype: int64

# 5. Envío promedio por tienda